version: '2'
services:
  web:
    build: .
    ports:
     - "80:80"
    environment:
      TERM:
      DB_TYPE: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: U5dk53HHqp
      DB_NAME: patchman
    depends_on:
      - db
  db:
    image: "mysql"
    environment:
      TERM:
      MYSQL_ROOT_PASSWORD: "${DB_PASS}"
      MYSQL_DATABASE: "${DB_NAME}"
